// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@goproxy.local"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/cache/invalidate": {
            "post": {
                "description": "Поддерживает режимы key, prefix, regex, tags и clear",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Инвалидировать кэш вручную",
                "parameters": [
                    {
                        "description": "Параметры инвалидации",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CacheInvalidationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CacheInvalidationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/ip-rules": {
            "get": {
                "description": "Белый, чёрный и серый списки",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Получить IP-правила доступа",
                "parameters": [
                    {
                        "enum": [
                            "allow",
                            "deny",
                            "grey"
                        ],
                        "type": "string",
                        "description": "Фильтр по типу",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.IPRulesResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Добавить IP-правило",
                "parameters": [
                    {
                        "description": "Новое правило",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.IPRuleCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.IPRuleResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/ip-rules/check": {
            "get": {
                "description": "Возвращает итоговое решение с учётом deny/allow/grey/default policy",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Проверить доступ для IP",
                "parameters": [
                    {
                        "type": "string",
                        "description": "IP адрес",
                        "name": "ip",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.IPAccessCheckResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/ip-rules/{ruleId}": {
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Удалить IP-правило",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID правила",
                        "name": "ruleId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/logs": {
            "get": {
                "description": "Буфер последних событий; полный архив — в logs/app.json (go-utils/zap)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Получить логи доступа",
                "parameters": [
                    {
                        "enum": [
                            "info",
                            "warning",
                            "error"
                        ],
                        "type": "string",
                        "description": "Уровень",
                        "name": "level",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "access",
                            "error",
                            "security"
                        ],
                        "type": "string",
                        "description": "Тип",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Количество записей",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.LogsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/metrics/cache": {
            "get": {
                "description": "Hits, misses, размер, инвалидации",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Получить метрики кэша",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CacheMetricsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/metrics/proxy": {
            "get": {
                "description": "RPS, latency, ошибки, активные соединения",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Получить метрики прокси",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ProxyMetricsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/metrics/system": {
            "get": {
                "description": "CPU, память, goroutines, GC",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Получить системные метрики",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SystemMetricsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/rate-limit/config": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Получить конфигурацию rate limit",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.RateLimitConfigResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Обновить конфигурацию rate limit",
                "parameters": [
                    {
                        "description": "Конфигурация",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RateLimitConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.RateLimitConfigResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/rate-limit/violators": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Список нарушителей rate limit",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.RateViolatorsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/upstream-servers": {
            "get": {
                "description": "Health, latency, error rate",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Статус upstream-серверов",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UpstreamServersResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/captcha/verify": {
            "post": {
                "description": "Статическая проверка 2 + 2. Верный ответ: 4",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Captcha"
                ],
                "summary": "Проверить CAPTCHA для серого списка",
                "parameters": [
                    {
                        "description": "Ответ на CAPTCHA",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CaptchaVerifyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CaptchaVerifyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/dto.CaptchaVerifyResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.CacheInvalidationRequest": {
            "type": "object",
            "required": [
                "mode"
            ],
            "properties": {
                "key": {
                    "type": "string"
                },
                "mode": {
                    "type": "string",
                    "enum": [
                        "key",
                        "prefix",
                        "regex",
                        "tags",
                        "clear"
                    ]
                },
                "pattern": {
                    "type": "string"
                },
                "prefix": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dto.CacheInvalidationResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.CacheInvalidationResult"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "dto.CacheInvalidationResult": {
            "type": "object",
            "properties": {
                "deleted": {
                    "type": "integer"
                },
                "mode": {
                    "type": "string"
                }
            }
        },
        "dto.CacheMetrics": {
            "type": "object",
            "properties": {
                "hits": {
                    "type": "integer"
                },
                "invalidations": {
                    "type": "integer"
                },
                "misses": {
                    "type": "integer"
                },
                "size": {
                    "type": "string"
                }
            }
        },
        "dto.CacheMetricsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.CacheMetrics"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "dto.CaptchaVerifyRequest": {
            "type": "object",
            "required": [
                "answer"
            ],
            "properties": {
                "answer": {
                    "type": "string"
                }
            }
        },
        "dto.CaptchaVerifyResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.CaptchaVerifyResult"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "dto.CaptchaVerifyResult": {
            "type": "object",
            "properties": {
                "allowed": {
                    "type": "boolean"
                },
                "ip": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                }
            }
        },
        "dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "invalid request"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "dto.IPAccessCheck": {
            "type": "object",
            "properties": {
                "allowed": {
                    "type": "boolean"
                },
                "grey": {
                    "type": "boolean"
                },
                "ip": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                }
            }
        },
        "dto.IPAccessCheckResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.IPAccessCheck"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "dto.IPRule": {
            "type": "object",
            "properties": {
                "addedDate": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "ip": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "requests": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "dto.IPRuleCreateRequest": {
            "type": "object",
            "required": [
                "ip",
                "reason",
                "type"
            ],
            "properties": {
                "ip": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "allow",
                        "deny",
                        "grey"
                    ]
                }
            }
        },
        "dto.IPRuleResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.IPRule"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "dto.IPRulesResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.IPRule"
                    }
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "dto.LogEntry": {
            "type": "object",
            "properties": {
                "ip": {
                    "type": "string"
                },
                "level": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "method": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "dto.LogsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.LogEntry"
                    }
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "dto.ProxyMetrics": {
            "type": "object",
            "properties": {
                "activeConnections": {
                    "type": "integer"
                },
                "avgLatency": {
                    "type": "number"
                },
                "errorRate": {
                    "type": "number"
                },
                "p99Latency": {
                    "type": "number"
                },
                "requestsPerSecond": {
                    "type": "number"
                },
                "totalRequests": {
                    "type": "integer"
                }
            }
        },
        "dto.ProxyMetricsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.ProxyMetrics"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "dto.RateLimitConfig": {
            "type": "object",
            "properties": {
                "banDuration": {
                    "type": "integer"
                },
                "maxConnections": {
                    "type": "integer"
                },
                "rpm": {
                    "type": "integer"
                },
                "rps": {
                    "type": "integer"
                }
            }
        },
        "dto.RateLimitConfigResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.RateLimitConfig"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "dto.RateViolator": {
            "type": "object",
            "properties": {
                "ip": {
                    "type": "string"
                },
                "limit": {
                    "type": "integer"
                },
                "requests": {
                    "type": "integer"
                },
                "violations": {
                    "type": "integer"
                }
            }
        },
        "dto.RateViolatorsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.RateViolator"
                    }
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "dto.SuccessResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.SystemMetrics": {
            "type": "object",
            "properties": {
                "cpu": {
                    "type": "number"
                },
                "gcPauses": {
                    "type": "number"
                },
                "goroutines": {
                    "type": "integer"
                },
                "memory": {
                    "type": "number"
                }
            }
        },
        "dto.SystemMetricsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.SystemMetrics"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "dto.UpstreamServer": {
            "type": "object",
            "properties": {
                "errorRate": {
                    "type": "number"
                },
                "lastCheck": {
                    "type": "string"
                },
                "latency": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "timeouts": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "dto.UpstreamServersResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.UpstreamServer"
                    }
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        }
    },
    "tags": [
        {
            "description": "Административные операции прокси-сервера",
            "name": "Admin"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "GoProxy Admin API",
	Description:      "REST API админ-панели reverse-proxy: метрики, IP-правила, логи, rate limit, upstream.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
